import * as XLSX from "xlsx";

import { normalizeDisease } from "./disease";

function sheetFromRows(rows) {
  return XLSX.utils.json_to_sheet(rows);
}

function sheetFromPairs(pairs) {
  return XLSX.utils.aoa_to_sheet(pairs);
}

function formatDateValue(value) {
  if (value == null || value === "") return "—";
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return String(value);
  try {
    return new Intl.DateTimeFormat("en-PH", {
      year: "numeric",
      month: "short",
      day: "2-digit"
    }).format(d);
  } catch {
    return String(value);
  }
}

function displayDisease(p) {
  const normalized = normalizeDisease(p?.diseaseType);
  if (normalized === "DENGUE") return "Dengue";
  if (normalized === "ILI") return "ILI";
  if (normalized === "AWD") return "AWD";
  return String(p?.diseaseType ?? "—").trim() || "—";
}

/** Full patient row for Excel — every field available from the API. */
export function patientRecordRow(p) {
  return {
    "Record ID": p?.id ?? "—",
    "Patient Name": String(p?.name ?? "—").trim() || "—",
    "Patient Number": String(p?.patientNumber ?? p?.patient_number ?? "—").trim() || "—",
    Age: p?.age ?? "—",
    Sex: p?.sex ?? "—",
    Birthdate: formatDateValue(p?.birthdate),
    "Civil Status": p?.civilStatus ?? "—",
    Province: p?.province ?? "—",
    Municipality: String(p?.municipality ?? "—").trim() || "—",
    Barangay: String(p?.barangay ?? "—").trim() || "—",
    Purok: p?.purok ?? "—",
    Birthplace: p?.birthplace ?? "—",
    Disease: displayDisease(p),
    "Case Classification": p?.caseClassification ?? "—",
    "Case Status": p?.caseStatus ?? "—",
    "Date of Onset": formatDateValue(p?.dateStarted),
    "Date Reported": formatDateValue(p?.createdAt ?? p?.created_at)
  };
}

function caseRow(c) {
  return patientRecordRow(c.raw ?? c);
}

/**
 * Build and download an Excel workbook for the Reports page.
 */
export function exportReportExcel({
  reportTitle,
  titleRange,
  coverageLabel,
  generatedBy,
  reportType,
  summary,
  municipalityRows,
  cases,
  allPatients,
  remarks
}) {
  const workbook = XLSX.utils.book_new();
  const reportCaseRows = (cases ?? []).map(caseRow);
  const allPatientRows = (allPatients ?? []).map(patientRecordRow);

  const summarySheet = sheetFromPairs([
    ["ALERTO Disease Surveillance Report"],
    [],
    ["Report title", reportTitle],
    ["Disease filter", reportType === "ALL" ? "All diseases" : reportType],
    ["Date range", titleRange],
    ["Coverage", coverageLabel],
    ["Generated by", generatedBy],
    ["Generated on", new Date().toLocaleString("en-PH")],
    [],
    ["Summary (report filters)"],
    ["Total cases", summary.total],
    ["Dengue cases", summary.dengue],
    ["ILI cases", summary.ili],
    ["AWD cases", summary.awd],
    ["Report cases exported", reportCaseRows.length],
    ["All patients exported", allPatientRows.length],
    [],
    ["Remarks", remarks]
  ]);
  XLSX.utils.book_append_sheet(workbook, summarySheet, "Summary");

  const municipalitySheet = sheetFromRows(
    municipalityRows.length
      ? municipalityRows.map((r) => ({
          Municipality: r.municipality,
          Dengue: r.dengue,
          ILI: r.ili,
          AWD: r.awd,
          Total: r.total
        }))
      : [{ Municipality: "No data for selected filters" }]
  );
  XLSX.utils.book_append_sheet(workbook, municipalitySheet, "By Municipality");

  const casesSheet = sheetFromRows(
    reportCaseRows.length
      ? reportCaseRows
      : [{ "Patient Name": "No cases for selected report filters" }]
  );
  XLSX.utils.book_append_sheet(workbook, casesSheet, "Report Cases");

  const patientsSheet = sheetFromRows(
    allPatientRows.length
      ? allPatientRows
      : [{ "Patient Name": "No patient records in your coverage area" }]
  );
  XLSX.utils.book_append_sheet(workbook, patientsSheet, "All Patients");

  const typeSlug = String(reportType ?? "all")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  const stamp = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(workbook, `alerto-${typeSlug || "all"}-report-${stamp}.xlsx`);
}
